# Generated by Django 5.1.4 on 2024-12-09 13:18

import social_links_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_apmo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/preachers/')),
                ('social_links', social_links_field.models.SocialLinksField(default=list)),
            ],
        ),
    ]
