# Generated by Django 5.1.4 on 2024-12-09 13:37

import social_links_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_apmo', '0002_preacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preacher',
            name='social_links',
            field=social_links_field.models.SocialLinksField(blank=True, default=list, null=True),
        ),
    ]
