# Generated by Django 5.1.4 on 2024-12-09 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_apmo', '0005_remove_playlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('date_published', models.DateField(verbose_name='Date Published')),
                ('audio_file_url', models.URLField(verbose_name='Audio File URL')),
                ('description', models.TextField(verbose_name='Description')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tags')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='Play Count')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likes Count')),
                ('bg_picture', models.ImageField(blank=True, null=True, upload_to='images/sermons/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='base_apmo.category', verbose_name='Category')),
                ('playlists', models.ManyToManyField(blank=True, related_name='sermons', to='base_apmo.playlist', verbose_name='Playlists')),
                ('preacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='base_apmo.preacher', verbose_name='Preacher')),
            ],
        ),
    ]
